program = declaration* EOF ;

declaration = varDecl | statement ;

varDecl = "var" IDENTIFIER "=" expression ";" ;

statement = exprStmt | printStmt | block | ifStmt | whileStmt | breakStmt | continueStmt ;

breakStmt = "break" ";" ;
continueStmt = "continue" ";" ;

whileStmt = "while" expression block ;

ifStmt = "if" expression block
       ( "else" "if" expression block )*
       ( "else" block )? ;
block = "{" declaration* "}" ;
exprStmt = expression ";" ;
printStmt = "print" expression ";" ;
