program = declaration* EOF ;

declaration = funDecl | varDecl | statement ;

funDecl = "fun" IDENTIFIER "(" parameters? ")" block ;
parameters = IDENTIFIER ( "," IDENTIFIER )* ;

varDecl = "var" IDENTIFIER "=" expression ";" ;

statement = exprStmt | printStmt | block | ifStmt | returnStmt | whileStmt | breakStmt | continueStmt ;

returnStmt = "return" expression ";" ;

breakStmt = "break" ";" ;
continueStmt = "continue" ";" ;

whileStmt = "while" expression block ;

ifStmt = "if" expression block
       ( "else" "if" expression block )*
       ( "else" block )? ;
block = "{" declaration* "}" ;
exprStmt = expression ";" ;
printStmt = "print" expression ";" ;
